"""empty message

Revision ID: c6054c283a92
Revises: 60818068f796
Create Date: 2023-05-05 22:59:24.909511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6054c283a92'
down_revision = '60818068f796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('id_sender', sa.Integer(), nullable=False),
    sa.Column('id_receiver', sa.Integer(), nullable=False),
    sa.Column('sent_date', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('id_sender', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_receiver', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sent_date', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='messages_pkey')
    )
    op.drop_table('message')
    # ### end Alembic commands ###
